# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RandomNumber(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, number: float=None):  # noqa: E501
        """RandomNumber - a model defined in Swagger

        :param id: The id of this RandomNumber.  # noqa: E501
        :type id: int
        :param number: The number of this RandomNumber.  # noqa: E501
        :type number: float
        """
        self.swagger_types = {
            'id': int,
            'number': float
        }

        self.attribute_map = {
            'id': 'id',
            'number': 'number'
        }
        self._id = id
        self._number = number

    @classmethod
    def from_dict(cls, dikt) -> 'RandomNumber':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RandomNumber of this RandomNumber.  # noqa: E501
        :rtype: RandomNumber
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this RandomNumber.


        :return: The id of this RandomNumber.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this RandomNumber.


        :param id: The id of this RandomNumber.
        :type id: int
        """

        self._id = id

    @property
    def number(self) -> float:
        """Gets the number of this RandomNumber.


        :return: The number of this RandomNumber.
        :rtype: float
        """
        return self._number

    @number.setter
    def number(self, number: float):
        """Sets the number of this RandomNumber.


        :param number: The number of this RandomNumber.
        :type number: float
        """

        self._number = number
